-- Real-world scenario: FriendIDs stored as comma-separated string
-- We need to "explode" that string into separate rows

CREATE TABLE #Friends (
	CustomerID INT,
	CustomerName VARCHAR(50),
	FriendIDs VARCHAR(100)  -- Stored as "1,2,3,4"
);

CREATE TABLE #Addresses (
	CustomerID INT,
	Address VARCHAR(100),
	priority INT
);

INSERT INTO #Friends VALUES 
(1, 'Alice', '2,3'),
(2, 'Bob', '1,4'),
(3, 'Carol', '1'),
(4, 'Dave', NULL);  -- Dave has no friends :(

INSERT INTO #Addresses VALUES 
(1, '123 Main St', 1),
(2, '456 Oak Ave', 1),
(3, '789 Pine Rd', 2),
(3, '321 Elm St', 1),  -- Carol has 2 addresses
(4, '654 Maple Dr', 1);

-- Let's see what we have and what string_split does
SELECT * FROM #Friends;
SELECT * FROM #Addresses;
SELECT * FROM STRING_SPLIT('2,3,4', ',');

-- KEY NOTE:
-- Scalar Valued Functions return a value. They are typically used in the SELECT or WHERE clause.
-- Table Valued Functions return a dataset. They are used in the FROM clause (or in CROSS/OUTER APPLY)

-- STEP 1: Split that comma-separated string into rows
-- CROSS APPLY lets us turn "2,3" into two separate rows
SELECT 
	f.CustomerName
	,f.FriendIDs
	,theSplitTbl.value AS FriendID
FROM #Friends f
CROSS APPLY STRING_SPLIT(f.FriendIDs, ',') AS theSplitTbl;
-- ^^ In coding terms: "For Each FriendIDs value, create a table (multiple rows) of each id (split by comma)"
-- ^^ Then, do an IMPLICIT join of that result on value (value is the column name auto-generated by string_split)
-- ^^ by IMPLICIT join, I mean, as if there were an invisible UniqueID present for each record on Friends.
	-- ^^ and as if string_split not only returned value but the same UniqueID, duplicated for each split, but invisible in the table
	-- ^^ then, the join is on that INVISIBLE UniqueID

-- we can also join the table to itself using cross apply
SELECT 
	*
FROM #Friends f
CROSS APPLY (
	select *
	from #Friends
) f2 -- FOR EACH record in Friends, return EACH RECORD in Friends. (this explode-Squares the resultset.)

-- INVALID
-- There's NO way to "JOIN" to a table-valued function. You must use cross/outer apply.
-- The problem is that STRING_SPLIT(f.FriendIDs, ',') needs f to exist first - but in a JOIN, both sides are evaluated independently. It's a chicken-and-egg problem
SELECT 
	f.CustomerName
	,f.FriendIDs
	,theSplitTbl.value AS FriendID
FROM #Friends f
join STRING_SPLIT(f.FriendIDs, ',') AS theSplitTbl on f.??? = theSplitTbl.invisibleUniqueID;
-- however, You can use JOIN with table-valued functions that don't reference the outer query:
SELECT *
FROM #Friends f
JOIN STRING_SPLIT('1,2,3', ',') AS theSplitTbl ON 1=1;
-- 1=1 is refering to that InvisibleUniqueID that "exists" on friends and that the table valued function, which can explode the result-set, uses to link the records back to the original table. However you need to think about it: either invisible unique id OR (in programming terms) FOR EACH record in the base query, do this operation and return the results (exploding the number of rows if necessary)

-- What happens if you don't give Cross Apply an alias? Well, you can't use it in the SELECT without one.
-- but, try this to see what happens w/out an alias. SQL auto-assigns "value" as the column name for split.
SELECT *
FROM #Friends f
CROSS APPLY STRING_SPLIT(f.FriendIDs, ',');
-- ^^ point being, if you want to USE it / alias the Value column returned, you need to alias the table returned from cross apply

-- STEP 2: Now join the table to itself via the circuitous rout of theSplitTbl to get friend names
-- Watch how CROSS APPLY makes this dead simple
SELECT 
	f.CustomerName AS Customer,
	f2.CustomerName AS FriendName,
	f.CustomerID,
	f2.CustomerID as FriendCustomerID
FROM #Friends f
CROSS APPLY STRING_SPLIT(f.FriendIDs, ',') AS theSplitTbl
JOIN #Friends f2 ON f2.CustomerID = CAST(theSplitTbl.value AS INT);

-- STEP 3: Now get ALL addresses for each friend

-- reminder of what we have
SELECT * FROM #Friends;
SELECT * FROM #Addresses;

-- can't we just get the address for each friend???
SELECT 
	f.CustomerName AS Customer,
	f2.CustomerName AS FriendName,
	f.CustomerID,
	f2.CustomerID,
	a.Address
FROM #Friends f
CROSS APPLY STRING_SPLIT(f.FriendIDs, ',') AS theSplitTbl
JOIN #Friends f2 ON f2.CustomerID = CAST(theSplitTbl.value AS INT)
join #Addresses a on a.CustomerID = value; -- joins on the output of the table-valued function

-- "This is where CROSS APPLY really shines - nested relationships" << Really? We just did a simple join before??
-- no, THIS is where CROSS APPLY really shines: the ability to join a table but 
SELECT 
	f.CustomerName AS Customer,
	f2.CustomerName AS FriendName,
	addr.Address AS FriendAddress
FROM #Friends f
CROSS APPLY STRING_SPLIT(f.FriendIDs, ',') AS theSplitTbl
JOIN #Friends f2 ON f2.CustomerID = CAST(theSplitTbl.value AS INT)
CROSS APPLY (
	SELECT Address
	FROM #Addresses
	WHERE CustomerID = f2.CustomerID
) addr; -- a new join with the potential to be tailored. 

-- reminder of what we have
SELECT * FROM #Friends;
SELECT * FROM #Addresses;

-- NO -- THIS is where CROSS APPLY really shines - a way to have a >>>tailored JOIN<<< utilizing TOP and ORDER BY.
SELECT 
	f.CustomerName AS Customer,
	friend.CustomerName AS FriendName,
	addr.Address AS FriendAddress
FROM #Friends f
CROSS APPLY STRING_SPLIT(f.FriendIDs, ',') AS theSplitTbl
JOIN #Friends friend ON friend.CustomerID = CAST(theSplitTbl.value AS INT)
CROSS APPLY (
	SELECT TOP 1 Address -- toggle between top 1 and top 2 to see how we can tailor the join.
	FROM #Addresses a
	WHERE CustomerID = friend.CustomerID
	ORDER BY a.priority DESC
) addr;

-- Notice: Carol has two addresses. If TOP 2 then she appears TWICE, if TOP 1, then she appears ONCE
-- Dave doesn't appear because he has no friends to split

DROP TABLE #Friends;
DROP TABLE #Addresses;